### ISSUE TITLE
Only advances once with volume buttons

### ISSUE THREAD

**Issue by gbishop** [google/watchpresenter#15]
It was working fine until recently. Now the volume buttons will only advance once, then no response.

The next slide button in the alert works still.

**Comment by pgilmon** [comment]
Which version of Android and of watchpresenter are you using?

**Comment by gbishop** [comment]
Android 5.1 kernel 3.4.42-g19638c4. 

Watch presenter 2.0.7

**Comment by charlesainslie** [comment]
Got the same problem. Following.

**Comment by pgilmon** [comment]
Introduced fix for Marshmallow that messed up volume button detection for <= Lollipop.

**Comment by pgilmon** [comment]
I have commited a fix for this bug. I'll upload a new version to the Play Store. You should receive the update in a few hours (check for version >= 2.0.8)

**Comment by pgilmon** [comment]
Sorry for the delay guys. Let me know if you still have trouble after the update
